name       : asunder
version    : 2.9.1
release    : 4
source     :
    - http://littlesvr.ca/asunder/releases/asunder-2.9.1.tar.bz2 : 401d29d2ea5e6a70cb1485edd6ae5bfaf495fc02d3f0322991c8d6cbbbb2c6fb
license    : GPL-2.0
component  : multimedia.audio
summary    : a graphical CD ripper and encoder
description: |
    Asunder is a graphical Audio CD ripper and encoder for Linux. You can use it to save tracks from an Audio CD as any of WAV, MP3, OGG, FLAC, Opus, WavPack, Musepack, AAC, and Monkey's Audio files.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libcddb)
    - intltool
rundeps    :
    - libcdio-paranoia
    - vorbis-tools
    - wavpack-utils
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
